FROM python:3.6

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE  1

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y dumb-init

RUN mkdir /app
WORKDIR /app
COPY . /app/

RUN pip install -r requirements.txt
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/app/entrypoint.dev.sh"]
